/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package game

import game.mafia.*
import game.mafia.users.*

fun main() {
    val games = mutableListOf<Mafia>()
    val host = Player("Host")

    val testGame = host.createGame("Test_Game", games)

    var i = 'a'
    val testPlayers = MutableList(8) { Player("${i++}") }

    for (player in testPlayers) {
        player.joinGame(testGame.gameId, games)
    }
    testPlayers.add(host)

    testGame.startGame()
}