/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package game

import org.junit.jupiter.api.Assertions.assertEquals
import kotlin.test.Test
import kotlin.test.assertNotNull


internal class MyFirstJUnitJupiterTests {
    @org.junit.jupiter.api.Test
    fun addition() {
        assertEquals(2, 2)
    }
}

//class AppTest {
//    @Test fun appHasAGreeting() {
//        val classUnderTest = App()
//        assertNotNull(classUnderTest.greeting, "app should have a greeting")
//    }
//}
