/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package game

import game.mafia.users.Player
import org.junit.jupiter.api.Assertions.assertEquals
import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertTrue


internal class MyFirstJUnitJupiterTests {
    @org.junit.jupiter.api.Test
    fun addition() {
        assertEquals(2, 2)
    }
}

class AppTest {
    @Test fun appHasAGreeting() {
        var player = Player("qwert")
        assertTrue(!player.isHost, "asd")
    }
}
